site_name: LightSpeed VT Documentation
pages:
- ['index.md', 'Home']
 # Boilerplate
- ['boilerplate/getting-started.md', 'Boilerplate', 'Getting Started']
- ['boilerplate/install.md', 'Boilerplate', 'Installation']
- ['boilerplate/setup.md', 'Boilerplate', 'Setup']
# Tutorial
- ['boilerplate/tutorial-intro.md', 'Boilerplate', 'Tutorial - Intro']
- ['boilerplate/tutorial-step-1.md', 'Boilerplate', 'Tutorial - Step 1']
- ['boilerplate/tutorial-step-2.md', 'Boilerplate', 'Tutorial - Step 2']
- ['boilerplate/tutorial-step-3.md', 'Boilerplate', 'Tutorial - Step 3']
- ['boilerplate/tutorial-hamburger.md', 'Boilerplate', 'Tutorial - Hamburger Menu']
- ['boilerplate/tutorial-page.md', 'Boilerplate', 'Tutorial - Page']
- ['boilerplate/tutorial-logo.md', 'Boilerplate', 'Tutorial - Logo']
- ['boilerplate/tutorial-nav.md', 'Boilerplate', 'Tutorial - Navigation']
- ['boilerplate/tutorial-user.md', 'Boilerplate', 'Tutorial - User Menu']
- ['boilerplate/tutorial-crumbs.md', 'Boilerplate', 'Tutorial - Crumb Menu']
- ['boilerplate/tutorial-footer.md', 'Boilerplate', 'Tutorial - Footer']
# Documentation
- ['boilerplate/docs.md', 'Boilerplate', 'Documentation']
- ['boilerplate/scss.md', 'Boilerplate', 'Using Custom SCSS']
- ['boilerplate/icons.md', 'Boilerplate', 'Icons']
theme: readthedocs
