site_name: LightSpeed VT - Boilerplate
pages:
 # Boilerplate
- ['index.md', 'Getting Started']
- ['changelog.md', 'Changelog']
- ['boilerplate/install.md', 'Configuration', 'Installation']
- ['boilerplate/setup.md', 'Configuration', 'Setup']
# Tutorial
- ['boilerplate/tutorial-intro.md', 'Tutorial', 'Intro']
- ['boilerplate/tutorial-step-1.md', 'Tutorial', 'Step 1 - Using Branches']
- ['boilerplate/tutorial-step-2.md', 'Tutorial', 'Step 2 - Using Grunt']
- ['boilerplate/tutorial-step-3.md', 'Tutorial', 'Step 3 - Editing Your Theme']
- ['boilerplate/tutorial-hamburger.md', 'Tutorial', 'Component - Hamburger Menu']
- ['boilerplate/tutorial-page.md', 'Tutorial', 'Component - Page']
- ['boilerplate/tutorial-logo.md', 'Tutorial', 'Component - Logo']
- ['boilerplate/tutorial-nav.md', 'Tutorial', 'Component - Navigation']
- ['boilerplate/tutorial-user.md', 'Tutorial', 'Component - User Menu']
- ['boilerplate/tutorial-crumbs.md', 'Tutorial', 'Component - Crumb Menu']
- ['boilerplate/tutorial-footer.md', 'Tutorial', 'Component - Footer']
# Documentation
- ['boilerplate/porting.md', 'Reference', 'Porting Existing Themes']
- ['boilerplate/publishing.md', 'Reference', 'Preview & Publish']
- ['boilerplate/docs.md', 'Reference', 'Documentation']
- ['boilerplate/specific-pages.md', 'Reference', 'Customizing Specific Pages']
- ['boilerplate/scss.md', 'Reference', 'Using Custom SCSS']
- ['boilerplate/icons.md', 'Reference', 'Icons']
theme: readthedocs
