site_name: LightSpeed VT Documentation
pages:
- ['index.md', 'Home']
- ['boilerplate/getting-started.md', 'Boilerplate', 'Getting Started']
- ['boilerplate/icons.md', 'Boilerplate', 'Icons']
theme: readthedocs
