site_name: LightSpeed VT - Boilerplate
pages:
 # Boilerplate
- ['changelog.md', 'Changelog']
- ['index.md', 'Getting Started']
- ['boilerplate/install.md', 'Configuration', 'Installation']
- ['boilerplate/setup.md', 'Configuration', 'Setup']
# Tutorial
- ['boilerplate/tutorial-intro.md', 'Tutorial', 'Introduction']
- ['boilerplate/tutorial-step-1.md', 'Tutorial', 'Creating Your Theme']
- ['boilerplate/tutorial-step-3.md', 'Tutorial', 'Editing Your Theme']
- ['boilerplate/tutorial-hamburger.md', 'Tutorial', 'Component - Hamburger Menu']
- ['boilerplate/tutorial-page.md', 'Tutorial', 'Component - Page']
- ['boilerplate/tutorial-logo.md', 'Tutorial', 'Component - Logo']
- ['boilerplate/tutorial-nav.md', 'Tutorial', 'Component - Navigation']
- ['boilerplate/tutorial-user.md', 'Tutorial', 'Component - User Menu']
- ['boilerplate/tutorial-crumbs.md', 'Tutorial', 'Component - Crumb Menu']
- ['boilerplate/tutorial-footer.md', 'Tutorial', 'Component - Footer']
# Next Steps
- ['boilerplate/tutorial-step-4.md', 'Next Steps', 'Previewing & Publishing Your Theme']
- ['boilerplate/editing-themes.md', 'Next Steps', 'Editing Existing Themes']
- ['boilerplate/porting.md', 'Next Steps', 'Porting Legacy Themes']
- ['boilerplate/specific-pages.md', 'Next Steps', 'Customizing Specific Pages']
- ['boilerplate/scss.md', 'Next Steps', 'Using Custom SCSS']
# Documentation
- ['boilerplate/docs.md', 'Reference', 'Documentation']
- ['boilerplate/icons.md', 'Reference', 'Icons']
# Design Patterns
- ['patterns/inline-navbar-behind.md', 'Design Patterns', 'Inline Logo w/Navbar Behind']
theme: readthedocs
